byzantine_error_config_file: configs/example/test_byz2_byzantine_error_config_file.pkl
distributed_mab_config_file: configs/example/test_byz2_distributed_mab_config_file.pkl
multi_armed_bandit_config_file: configs/example/test_byz2_multi_armed_bandit_config_file.pkl
network_latency_config_file: configs/example/test_byz2_network_latency_config_file.pkl
round_config_file: configs/example/test_byz2_round_config_file.pkl
run_config_file: configs/example/test_byz2_run_config_file.pkl
