byzantine_error_config_file: configs/example/test_byz_byzantine_error_config_file.pkl
distributed_mab_config_file: configs/example/test_byz_distributed_mab_config_file.pkl
multi_armed_bandit_config_file: configs/example/test_byz_multi_armed_bandit_config_file.pkl
network_latency_config_file: configs/example/test_byz_network_latency_config_file.pkl
round_config_file: configs/example/test_byz_round_config_file.pkl
run_config_file: configs/example/test_byz_run_config_file.pkl
