byzantine_error_config_file: configs/project_experiments/fewer_rounds_exp_n_13_max_m_4_v4_byzantine_error_config_file.pkl
distributed_mab_config_file: configs/project_experiments/fewer_rounds_exp_n_13_max_m_4_v4_distributed_mab_config_file.pkl
multi_armed_bandit_config_file: configs/project_experiments/fewer_rounds_exp_n_13_max_m_4_v4_multi_armed_bandit_config_file.pkl
network_latency_config_file: configs/project_experiments/fewer_rounds_exp_n_13_max_m_4_v4_network_latency_config_file.pkl
round_config_file: configs/project_experiments/fewer_rounds_exp_n_13_max_m_4_v4_round_config_file.pkl
run_config_file: configs/project_experiments/fewer_rounds_exp_n_13_max_m_4_v4_run_config_file.pkl
