byzantine_error_config_file: configs/project_experiments/test_n_10_max_m_3_g0.6_f-3_byzantine_error_config_file.pkl
distributed_mab_config_file: configs/project_experiments/test_n_10_max_m_3_g0.6_f-3_distributed_mab_config_file.pkl
multi_armed_bandit_config_file: configs/project_experiments/test_n_10_max_m_3_g0.6_f-3_multi_armed_bandit_config_file.pkl
network_latency_config_file: configs/project_experiments/test_n_10_max_m_3_g0.6_f-3_network_latency_config_file.pkl
round_config_file: configs/project_experiments/test_n_10_max_m_3_g0.6_f-3_round_config_file.pkl
run_config_file: configs/project_experiments/test_n_10_max_m_3_g0.6_f-3_run_config_file.pkl
